custom:
  sim_num: 2403
default:
  ai_version_file: next_ai_version.txt
  batch_size: 1000
  board_height: 20
  board_square: 16
  board_width: 20
  checkpoint_freq: 50
  data_dir: sim_data
  discount: 0.83
  epsilon_enabled: false
  epsilon_print_stats: 1
  epsilon_value: 50
  game_speed: 500
  game_title: AI Snake Game
  headless: 0
  hidden_size: 270
  input_size: 400
  learning_rate: 0.001 # Was 0.001
  linear_input_size: 27
  log_basename: _log.txt
  matplot_max_x: 1000
  max_epochs: 0
  max_memories: 50
  max_memory: 100000
  max_moves: 100
  model: linear
  model_basename: _model.pth
  model_stats: true
  next_num_file: next_num.txt
  nu_bad_games: 6
  nu_enabled: true
  nu_high_grace: 3
  nu_max_epochs: 45
  nu_pool: 5
  nu_score: 0
  nu_verbose: false
  output_size: 3
  plot_basename: _plot.png
  plot_dir: sim_plots
  random_seed: 129
  reward_excessive_move: -10
  reward_food: 10
  reward_move: 0
  reward_snake_collision: -10
  reward_wall_collision: -10
  rnn_layers: 1
  rnnt_hidden_size: 128
  rnnt_input_size: 20
  rnnt_layers: 3
  rnnt_sequence_length: 20
  sim_highscore_basename: _highscore.csv
  sim_num: 1000
  sim_plot_basename: _plot.png
  stats_basename: _stats.yml
  status_iter: 50
  t_hidden_size: 270
  trainer_stats: true
