default:
  ai_version_file: next_ai_version.txt
  batch_size: 1000
  board_height: 20
  board_width: 20
  board_square: 20
  data_dir: sim_data
  discount: 0.83
  epsilon_enabled: False
  epsilon_print_stats: 1
  epsilon_value: 38
  game_speed: 500
  headless: 0
  hidden_size: 270
  input_size: 400
  learning_rate: 0.001
  linear_input_size: 27
  log_basename: _log.txt
  matplot_max_x: 1000
  max_epochs: 0
  max_moves: 100
  max_memory: 100000
  model: linear
  next_num_file: next_num.txt
  nu_pool: 5
  nu_bad_games: 5
  nu_high_grace: 3
  nu_enabled: True
  nu_max_epochs: 40
  nu_score: 0
  nu_verbose: False
  output_size: 3
  plot_basename: _plot.png
  plot_dir: sim_plots
  random_seed: 1970
  reward_food: 20
  reward_excessive_move: -20
  reward_wall_collision: -20
  reward_snake_collision: -20
  rnn_layers: 1
  sim_highscore_basename: _highscore.csv
  sim_num: 1000
  sim_plot_basename: _plot.png
  stats_basename: _stats.yml
  status_iter: 50
  t_hidden_size: 800
  game_title: AI Snake Game
